services:
  web:
    image: gcr.io/music-graph-479719/music-graph:production
    env_file:
      - .env.prod
    ports:
      - "127.0.0.1:5000:5000"  # Only localhost (Nginx will proxy)
    restart: unless-stopped
    environment:
      - ENVIRONMENT=prod
