services:
  web:
    image: gcr.io/music-graph-479719/music-graph:dev-latest
    env_file:
      - .env.dev
    ports:
      - "127.0.0.1:5000:5000"  # Nginx will proxy to this
    restart: unless-stopped
    environment:
      - ENVIRONMENT=dev
      - FLASK_ENV=development
      - FLASK_DEBUG=1
